### ISSUE TITLE
An idea about hotkey support

### ISSUE THREAD

**Issue by ojqpsk** [3C0D/obsidian-easy-toggle-sidebars#3]
hi, thanks to your great plugin! It brings great efficiency.

I have an idea, could it support open/hide left or right sidebas by hotkey like ctrl+o(open/hide left sidebar), ctrl+p(open/hide right sidebar)? I have this question because I'm a writer. Usually I want to keep my hands on my keyboard without touching my mouse. If your plugin could support open/hide left or right sidebar by hotkeys, it will bring more efficiency to the users who are more comfortable working without mouse.

Thanks a lot!

**Comment by 3C0D** [comment]
it's already in obsidian open command palette and type sidebar. you can add some shortcuts going in shortcuts settings
